steps:
 - name: ':$TARGET, ${CXX} :docker: :rocket:'
   command: feelpp/tools/scripts/buildkite/install-feelpp.sh feelpp
   if: build.message !~ /skip feelpp/
   agents:
     docker: true
#   artifact_paths: Testing/junit-*.xml
 - wait: ~
   if: build.message !~ /skip feelpp/
   continue_on_failure: false
 #- plugins:
 #    junit-annotate#v1.7.0:
 #      artifacts: Testing/junit-*.xml
 #      fail-build-on-error: true
 #  if: build.message !~ /skip feelpp/
 - trigger: "pkg-feelpp"
   label: ":package: :debian: :ubuntu: Feel++ ${BUILDKITE_BRANCH}"
   async: true
   if: |
     ( pipeline.slug=="feelpp" && ( build.branch == "develop" || build.branch == "master" )) && 
     build.message !~ /skip feelpp/
 - wait
 - name: ':$TARGET, $CXX, feelpp-testsuite :hammer: :docker: :rocket:'
   command: feelpp/tools/scripts/buildkite/install-feelpp.sh testsuite
   if: |
     build.message !~ /skip tests/ &&
     build.message !~ /skip components/ 
   agents:
     docker: true
 - name: ':$TARGET, $CXX, feelpp-toolboxes :hammer: :docker: :rocket:'
   command: feelpp/tools/scripts/buildkite/install-feelpp.sh toolboxes
   if: |
     build.message !~ /skip toolboxes/ &&
     build.message !~ /skip components/
   agents:
     docker: true
 - wait
 - name: ':$TARGET, $CXX, feelpp-mor :hammer: :docker: :rocket:'
   command: feelpp/tools/scripts/buildkite/install-feelpp.sh mor
   if: |
     (build.message !~ /skip mor/) &&
     (build.message !~ /skip components/)
   agents:
     docker: true
 - wait
 - name: ':$TARGET, $CXX, feelpp-python :python: :hammer: :docker: :rocket:'
   command: feelpp/tools/scripts/buildkite/install-feelpp.sh feelpp-python
   if: |
     (build.message !~ /skip python/) &&
     (build.message !~ /skip components/)
   agents:
     docker: true