steps:
 - name: ':$TARGET, ${CXX} :docker: :rocket:'
   command: feelpp/tools/scripts/buildkite/install-feelpp.sh feelpp
   if: build.message !~ /skip feelpp/
   agents:
     docker: true
   artifact_paths: Testing/junit-*.xml
 - wait: ~
   if: build.message !~ /skip feelpp/
   continue_on_failure: false
 - plugins:
     junit-annotate#v1.7.0:
       artifacts: Testing/junit-*.xml
       fail-build-on-error: true
   if: build.message !~ /skip feelpp/
 - wait
 - trigger: "pkg-feelpp"
   label: ":package: :debian: :ubuntu: Feel++ ${BUILDKITE_BRANCH}"
   async: true
   if: |
     ( pipeline.slug=="feelpp" && ( build.branch == "develop" || build.branch == "master" )) && 
     build.message !~ /skip feelpp/
 - wait
# # - trigger: "feelpp-singularity"
# #   label: ":package: :singularity: Feel++ feelpp ${BUILDKITE_BRANCH} containers"
# #   async: true
# #   build:
# #     env:
# #       GIRDER_ID: "5a4fa90ab0e9571f842931e5"
# #       PROJECT: "feelpp"
# #       TAG: ${BUILDKITE_BRANCH}
 - trigger: "feelpp-testsuite"
   label: ":docker: compile and run the Feel++ testsuite :rocket:"
   async: true
   if: |
     build.message !~ /skip tests/ &&
     build.message !~ /skip components/ &&
     ( build.branch == "master" || build.branch == "develop" )
   build:
    message: "${BUILDKITE_MESSAGE}"
    commit: "${BUILDKITE_COMMIT}"
    branch: "${BUILDKITE_BRANCH}"
 - name: ':$TARGET, $CXX, feelpp-toolboxes :hammer: :docker: :rocket:'
   command: feelpp/tools/scripts/buildkite/install-feelpp.sh toolboxes
   if: |
     build.message !~ /skip toolboxes/ &&
     build.message !~ /skip components/
   agents:
     docker: true
 - wait
 - trigger: "pkg-feelpp-toolboxes"
   label: ":package: :debian: :ubuntu: Feel++ Toolboxes ${BUILDKITE_BRANCH}"
   async: true
   if: |
     ((build.message !~ /skip toolboxes/) &&
     (build.message !~ /skip components/)) &&
     (pipeline.slug=="feelpp" && ( build.branch == "develop" || build.branch == "master" ))
# #  - wait
# # # - trigger: "feelpp-singularity"
# # #   label: ":package: :singularity: Feel++ Toolboxes ${BUILDKITE_BRANCH} containers"
# # #   async: true
# # #   build:
# # #     env:
# # #       GIRDER_ID: "5a4fa90ab0e9571f842931e5"
# # #       PROJECT: "feelpp-toolboxes"
# # #       TAG: ${BUILDKITE_BRANCH}
 - name: ':$TARGET, $CXX, feelpp-mor :hammer: :docker: :rocket:'
   command: feelpp/tools/scripts/buildkite/install-feelpp.sh mor
   if: |
     (build.message !~ /skip mor/) &&
     (build.message !~ /skip components/)
   agents:
     docker: true
# - wait
 - trigger: "pkg-feelpp-mor"
   label: ":package: :debian: :ubuntu: Feel++ MOR ${BUILDKITE_BRANCH}"
   async: true
   if: |
     ((build.message !~ /skip mor/) &&
     (build.message !~ /skip components/)) &&
     (pipeline.slug=="feelpp" && ( build.branch == "develop" || build.branch == "master" ))

# # - wait
# #- trigger: "feelpp-singularity"
# #  label: ":package: :singularity: Feel++ MOR ${BUILDKITE_BRANCH} containers"
# #  async: true
# #  build:
# #    env:
# #      GIRDER_ID: "5a4fa90ab0e9571f842931e5"
# #      PROJECT: "feelpp-mor"
# #      TAG: ${BUILDKITE_BRANCH}
# # notify:
# #   - slack: #env-buildkite
# 